# ALGORITMO DE NAIVE BAYES

> Análisis de sentimientos en un texto

#### Importación de librerías

In [36]:
import pandas as pd
from sklearn.naive_bayes import GaussianNB, MultinomialNB, BernoulliNB
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics import accuracy_score, classification_report
from sklearn.model_selection import GridSearchCV
from pickle import dump

#### Carga de datos

In [4]:
df = pd.read_csv("../data/raw/playstore_reviews.csv")
df

,package_name,review,polarity
0,com.facebook.katana,privacy at least put some option appear offli...,0
1,com.facebook.katana,"messenger issues ever since the last update, ...",0
2,com.facebook.katana,profile any time my wife or anybody has more ...,0
3,com.facebook.katana,the new features suck for those of us who don...,0
4,com.facebook.katana,forced reload on uploading pic on replying co...,0
...,...,...,...
886,com.rovio.angrybirds,loved it i loooooooooooooovvved it because it...,1
887,com.rovio.angrybirds,all time legendary game the birthday party le...,1
888,com.rovio.angrybirds,ads are way to heavy listen to the bad review...,0
889,com.rovio.angrybirds,fun works perfectly well. ads aren't as annoy...,1
890,com.rovio.angrybirds,they're everywhere i see angry birds everywhe...,1

In [6]:
df.columns

Index(['package_name', 'review', 'polarity'], dtype='object')

#### Procesamiento de datos

##### Eliminar espacios y transformar todo a minúsculas

In [7]:
df["review"] = df["review"].str.strip().str.lower()

#### Identificacion de columnas

In [14]:
X = df["review"]
y = df["polarity"]

#### División en entrenamiento y prueba

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

#### Transformar el texto en una matriz

In [16]:
vec_model = CountVectorizer(stop_words = "english")
X_train = vec_model.fit_transform(X_train).toarray()
X_test = vec_model.transform(X_test).toarray()

In [17]:
X_train

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(712, 3310))

### Modelado

> Multinomial

In [19]:
multi_nb = MultinomialNB()
multi_nb.fit(X_train, y_train)
y_pred_multi = multi_nb.predict(X_test)
y_pred_multi

array([0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0])

> Gaussian

In [20]:
gauss_nb = GaussianNB()
gauss_nb.fit(X_train, y_train)
y_pred_gauss = gauss_nb.predict(X_test)
y_pred_gauss

array([0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1,
       0, 0, 0])

> Bernoulli

In [23]:
bernoulli_nb = BernoulliNB()
bernoulli_nb.fit(X_train, y_train)
y_pred_bern = bernoulli_nb.predict(X_test)
y_pred_bern

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0])

#### Observación de resultados

In [25]:
print("MultinomialNB")
print("Accuracy:", accuracy_score(y_test, y_pred_multi))
print(classification_report(y_test, y_pred_multi))

print("GaussianNB")
print("Accuracy:", accuracy_score(y_test, y_pred_gauss))
print(classification_report(y_test, y_pred_gauss))

print("BernoulliNB")
print("Accuracy:", accuracy_score(y_test, y_pred_bern))
print(classification_report(y_test, y_pred_bern))

MultinomialNB
Accuracy: 0.8156424581005587
              precision    recall  f1-score   support

           0       0.84      0.90      0.87       126
           1       0.73      0.60      0.66        53

    accuracy                           0.82       179
   macro avg       0.79      0.75      0.77       179
weighted avg       0.81      0.82      0.81       179

GaussianNB
Accuracy: 0.8044692737430168
              precision    recall  f1-score   support

           0       0.85      0.88      0.86       126
           1       0.69      0.62      0.65        53

    accuracy                           0.80       179
   macro avg       0.77      0.75      0.76       179
weighted avg       0.80      0.80      0.80       179

BernoulliNB
Accuracy: 0.770949720670391
              precision    recall  f1-score   support

           0       0.79      0.93      0.85       126
           1       0.70      0.40      0.51        53

    accuracy                           0.77       179
   macro avg       0.74      0.66      0.68       179
weighted avg       0.76      0.77      0.75       179

In [28]:
results = {
    "Modelo": ["MultinomialNB", "GaussianNB", "BernoulliNB"],
    "Accuracy": [
        accuracy_score(y_test, y_pred_multi),
        accuracy_score(y_test, y_pred_gauss),
        accuracy_score(y_test, y_pred_bern)
    ],
    "F1-score": [
        classification_report(y_test, y_pred_multi, output_dict=True)["weighted avg"]["f1-score"],
        classification_report(y_test, y_pred_gauss, output_dict=True)["weighted avg"]["f1-score"],
        classification_report(y_test, y_pred_bern, output_dict=True)["weighted avg"]["f1-score"]
    ]}

In [29]:
df_resultados = pd.DataFrame(results)
df_resultados

          Modelo  Accuracy  F1-score
0  MultinomialNB  0.815642  0.810268
1     GaussianNB  0.804469  0.801531
2    BernoulliNB  0.770950  0.748792

#### De acuerdo a la tabla justificamos la elecciónd el modelo más adecuado para el análisis de sentimientos; elegimos el modelo con el F1-score y accuracy más altos.  Lo cual coincide con el modelo MultinomialNB, que es el recomendado teóricamente para clasificación de texto.

## Opcional:

> Optimización

In [32]:
params = {'alpha': [0.1, 0.5, 1.0, 2.0]}
grid = GridSearchCV(MultinomialNB(), params, cv=3)
grid.fit(X_train, y_train)
grid.best_params_

{'alpha': 0.5}

#### Re-entrenamos el modelo con el mejor alpha

In [33]:
best_alpha = grid.best_params_['alpha']
multi_nb_opt = MultinomialNB(alpha=best_alpha)
multi_nb_opt.fit(X_train, y_train)
y_pred_multi_opt = multi_nb_opt.predict(X_test)

#### Resultados optimizados

In [34]:
print("MultinomialNB Optimizado")
print("Accuracy:", accuracy_score(y_test, y_pred_multi_opt))
print(classification_report(y_test, y_pred_multi_opt))

MultinomialNB Optimizado
Accuracy: 0.8268156424581006
              precision    recall  f1-score   support

           0       0.86      0.90      0.88       126
           1       0.73      0.66      0.69        53

    accuracy                           0.83       179
   macro avg       0.80      0.78      0.79       179
weighted avg       0.82      0.83      0.82       179

### Guardar modelo

In [38]:
dump(multi_nb_opt, open("naive_bayes_sentimientos.sav", "wb"))